Set up cldr-runner to operate on an Ubuntu host
cloudera-labs/cldr-runner pull request #75
Opened 2024-01-05 16:47 UTC by wmudge

In order to run `ansible-navigator` and other `ansible-runner`-enabled applications on a Ubuntu host, rather than within a container via Docker.

2024-01-18 18:06 UTC, jimright requested changes
Hey @wmudge,

I've tested this by spinning up some EC2 instances for RHEL9 & Ubuntu (both 20.04 and 22.04) and running the scripts from the command line.
I also tested using these scripts as user data inputs. 

See my comments for some suggested changes.

As the script needs to be executed with elevated privileges (e.g. `sudo ...`), one thing that might also be worth considering is how to get the .bashrc prompt for the executing user. 
You could capture this using something like `login_user=${SUDO_USER:-$USER}` or by adding sudo on only commands that require it.

2024-02-02 17:23 UTC, wmudge commented on NAVIGATOR.md
> +* `ubuntu20-init-base.sh` (Ubuntu 20.04 LTS)
Added a CASE statement based on the output of `lsb_release`.

2024-02-02 21:33 UTC, wmudge commented on rhel9-init-base.sh
> +cat <<EOF >> ~/.bashrc
Added to the global bashrc along with additional instructions for enabling the virtual environment

2024-02-29 16:47 UTC, jimright approved these changes
Looks good. Approved

2024-02-29 16:56 UTC, merged